/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2_compi2;

import Ejecucion_D.Ejecutor;
import Gramatica_Pila.PilaGenerica;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author anton
 */
public class Mostrar_Stack extends javax.swing.JFrame {

    /**
     * Creates new form Stack
     */
    public static PilaGenerica pila_nueva;
    public Mostrar_Stack(PilaGenerica pila_nueva) {
        initComponents();
        this.pila_nueva=pila_nueva;
        cargarPilaAuxiliar();
        cargarPila();
        cargarPilaHeap();
    }
    public void cargarPilaAuxiliar(){
        String[] columnNames = {"Contenido"};
        //pila auxiliar
        Object[][] data=new Object[pila_nueva.pilaaux.size()][1];
        for(int i=0;i<pila_nueva.pilaaux.size();i++){
            data[i][0]=pila_nueva.pilaaux.get(i);
        }
        JTable jtable = new JTable(data, columnNames);
        jtable.setName("tabla_auxiliar");
        JScrollPane scrollPane = new JScrollPane(jtable);
        scrollPane.setSize(150,400);
        scrollPane.setLocation(60, 50);
        scrollPane.setName("pila_auxiliar");
        jtable.setFillsViewportHeight(true);
        this.add(scrollPane);
    }
    public void cargarPila(){
//        String[] columnNames = {"Contenido"};
//        //pila auxiliar
//        Object[][] data=new Object[Principal.pila.size()][1];
//        for(int i=0;i<Principal.pila.size();i++){
//            data[i][0]=Principal.pila.get(i);
//        }
//        JTable jtable = new JTable(data, columnNames);
//        jtable.setName("tabla_pila");
//        JScrollPane scrollPane = new JScrollPane(jtable);
//        scrollPane.setSize(150,400);
//        scrollPane.setLocation(335, 50);
//        scrollPane.setName("pila");
//        jtable.setFillsViewportHeight(true);
//        this.add(scrollPane);
    }
    public void cargarPilaHeap(){
//        String[] columnNames = {"Contenido"};
//        //pila auxiliar
//        Object[][] data=new Object[Principal.heap.size()][1];
//        for(int i=0;i<Principal.heap.size();i++){
//            data[i][0]=Principal.heap.get(i);
//        }
//        JTable jtable = new JTable(data, columnNames);
//        jtable.setName("tabla_heap");
//        JScrollPane scrollPane = new JScrollPane(jtable);
//        scrollPane.setSize(150,400);
//        scrollPane.setLocation(600, 50);
//        scrollPane.setName("heap");
//        jtable.setFillsViewportHeight(true);
//        this.add(scrollPane);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("PILA AUXILIAR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("HEAP");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("PILA");

        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Mostrar_Stack nuevo=new Mostrar_Stack(pila_nueva);
        nuevo.setVisible(true);
        nuevo.show();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
