
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 04 14:19:23 CST 2018
//----------------------------------------------------

package Gramatica_DASM;

/** CUP generated class containing symbol constants. */
public class simbolo_DASM {
  /* terminals */
  public static final int numero_completo = 2;
  public static final int i_entero = 33;
  public static final int call = 31;
  public static final int palabra = 4;
  public static final int function = 28;
  public static final int add = 7;
  public static final int mod = 11;
  public static final int oval = 38;
  public static final int calc = 35;
  public static final int eqz = 16;
  public static final int gte = 15;
  public static final int gt = 13;
  public static final int line = 41;
  public static final int i_flotante = 34;
  public static final int set_global = 25;
  public static final int tee_global = 27;
  public static final int end = 29;
  public static final int tee_local = 26;
  public static final int numero_decimal = 6;
  public static final int quadrate = 37;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int diff = 8;
  public static final int lt = 12;
  public static final int or = 18;
  public static final int lte = 14;
  public static final int i_caracter = 32;
  public static final int point = 40;
  public static final int br_if = 21;
  public static final int mult = 9;
  public static final int get_global = 23;
  public static final int texto = 39;
  public static final int and = 17;
  public static final int br = 20;
  public static final int not = 19;
  public static final int dolar = 3;
  public static final int get_local = 22;
  public static final int print = 30;
  public static final int div = 10;
  public static final int principal = 5;
  public static final int retorno = 36;
  public static final int set_local = 24;
}

